DROP TABLE SYS_PARAM;;

CREATE TABLE SYS_PARAM(
    CODE_ VARCHAR2(32) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    VALUE_ VARCHAR2(500) NOT NULL,
    SORT_ INT NOT NULL,
    PRIMARY KEY (CODE_)
);;

COMMENT ON TABLE SYS_PARAM IS '参数表';;
COMMENT ON COLUMN SYS_PARAM.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_PARAM.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_PARAM.VALUE_ IS '内容';;
COMMENT ON COLUMN SYS_PARAM.SORT_ IS '顺序';;

DROP TABLE SYS_DICT;;

CREATE TABLE SYS_DICT(
    ID_ VARCHAR2(32) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    SORT_ INT NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_DICT IS '字典表';;
COMMENT ON COLUMN SYS_DICT.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_DICT.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_DICT.SORT_ IS '顺序';;
COMMENT ON COLUMN SYS_DICT.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_DICT.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_DICT.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_DICT.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_DICT.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_DICT_ITEM;;

CREATE TABLE SYS_DICT_ITEM(
    ID_ VARCHAR2(32) NOT NULL,
    DICT_ID VARCHAR2(32) NOT NULL,
    CODE_ VARCHAR2(10) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    SORT_ INT NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_DICT_ITEM IS '字典项目表';;
COMMENT ON COLUMN SYS_DICT_ITEM.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_DICT_ITEM.DICT_ID IS '类型';;
COMMENT ON COLUMN SYS_DICT_ITEM.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_DICT_ITEM.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_DICT_ITEM.SORT_ IS '顺序';;
COMMENT ON COLUMN SYS_DICT_ITEM.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_DICT_ITEM.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_DICT_ITEM.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_DICT_ITEM.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_DICT_ITEM.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_ORGAN;;

CREATE TABLE SYS_ORGAN(
    ID_ VARCHAR2(32) NOT NULL,
    CODE_ VARCHAR2(50) NOT NULL,
    NAME_ VARCHAR2(200) NOT NULL,
    PID_ VARCHAR2(32) NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_ORGAN IS '机构表';;
COMMENT ON COLUMN SYS_ORGAN.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_ORGAN.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_ORGAN.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_ORGAN.PID_ IS '上级ID';;
COMMENT ON COLUMN SYS_ORGAN.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_ORGAN.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_ORGAN.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_ORGAN.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_ORGAN.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_RES;;

CREATE TABLE SYS_RES(
    ID_ VARCHAR2(32) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    TYPE_ VARCHAR2(10) NOT NULL,
    ICON_ VARCHAR2(50),
    URL_ VARCHAR2(500),
    SORT_ INT NOT NULL,
    SHOW_ VARCHAR2(10) NOT NULL,
    PID_ VARCHAR2(32) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_RES IS '资源表';;
COMMENT ON COLUMN SYS_RES.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_RES.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_RES.TYPE_ IS '类型';;
COMMENT ON COLUMN SYS_RES.ICON_ IS '图标';;
COMMENT ON COLUMN SYS_RES.URL_ IS '路径';;
COMMENT ON COLUMN SYS_RES.SORT_ IS '顺序';;
COMMENT ON COLUMN SYS_RES.SHOW_ IS '显示';;
COMMENT ON COLUMN SYS_RES.PID_ IS '上级ID';;

DROP TABLE SYS_ROLE;;

CREATE TABLE SYS_ROLE(
    ID_ VARCHAR2(32) NOT NULL,
    CODE_ VARCHAR2(50) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    PID_ VARCHAR2(32) NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_ROLE IS '角色表';;
COMMENT ON COLUMN SYS_ROLE.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_ROLE.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_ROLE.NAME_ IS '名称';;
COMMENT ON COLUMN SYS_ROLE.PID_ IS '上级ID';;
COMMENT ON COLUMN SYS_ROLE.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_ROLE.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_ROLE.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_ROLE.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_ROLE.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_ROLE_RES;;

CREATE TABLE SYS_ROLE_RES(
    ID_ VARCHAR2(32) NOT NULL,
    ROLE_ID VARCHAR2(32) NOT NULL,
    RES_ID VARCHAR2(32) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_ROLE_RES IS '角色资源表';;
COMMENT ON COLUMN SYS_ROLE_RES.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_ROLE_RES.ROLE_ID IS '角色ID';;
COMMENT ON COLUMN SYS_ROLE_RES.RES_ID IS '资源ID';;

DROP TABLE SYS_USER;;

CREATE TABLE SYS_USER(
    ID_ VARCHAR2(32) NOT NULL,
    ACCOUNT_ VARCHAR2(50) NOT NULL,
    PASSWORD_ VARCHAR2(32) NOT NULL,
    NAME_ VARCHAR2(50) NOT NULL,
    LOCKED_ VARCHAR2(10) NOT NULL,
    ORGAN_ID VARCHAR2(32) NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_USER IS '用户表';;
COMMENT ON COLUMN SYS_USER.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_USER.ACCOUNT_ IS '帐号';;
COMMENT ON COLUMN SYS_USER.PASSWORD_ IS '密码';;
COMMENT ON COLUMN SYS_USER.NAME_ IS '姓名';;
COMMENT ON COLUMN SYS_USER.LOCKED_ IS '是否锁定';;
COMMENT ON COLUMN SYS_USER.ORGAN_ID IS '机构ID';;
COMMENT ON COLUMN SYS_USER.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_USER.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_USER.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_USER.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_USER.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_USER_ORGAN;;

CREATE TABLE SYS_USER_ORGAN(
    ID_ VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(32) NOT NULL,
    ORGAN_ID VARCHAR2(32) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_USER_ORGAN IS '用户机构表';;
COMMENT ON COLUMN SYS_USER_ORGAN.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_USER_ORGAN.USER_ID IS '用户ID';;
COMMENT ON COLUMN SYS_USER_ORGAN.ORGAN_ID IS '机构ID';;

DROP TABLE SYS_USER_ROLE;;

CREATE TABLE SYS_USER_ROLE(
    ID_ VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(32) NOT NULL,
    ROLE_ID VARCHAR2(32) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_USER_ROLE IS '用户角色表';;
COMMENT ON COLUMN SYS_USER_ROLE.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';;
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';;

DROP TABLE SYS_USER_RES;;

CREATE TABLE SYS_USER_RES(
    ID_ VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(32) NOT NULL,
    RES_ID VARCHAR2(32) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_USER_RES IS '用户资源表';;
COMMENT ON COLUMN SYS_USER_RES.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_USER_RES.USER_ID IS '用户ID';;
COMMENT ON COLUMN SYS_USER_RES.RES_ID IS '资源ID';;

DROP TABLE SYS_LOG;;

CREATE TABLE SYS_LOG(
    ID_ VARCHAR2(32) NOT NULL,
    TYPE_ VARCHAR2(10) NOT NULL,
    CONTENT_ VARCHAR2(200) NOT NULL,
    CLIENT_IP VARCHAR2(100) NOT NULL,
    REQUEST_URL VARCHAR2(200) NOT NULL,
    REQUEST_PARAM CLOB,
    RESPONSE_RESULT CLOB NOT NULL,
    EXECUTE_METHOD VARCHAR2(500) NOT NULL,
    EXECUTE_TIME NUMBER NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_LOG IS '日志表';;
COMMENT ON COLUMN SYS_LOG.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_LOG.TYPE_ IS '类型';;
COMMENT ON COLUMN SYS_LOG.CONTENT_ IS '内容';;
COMMENT ON COLUMN SYS_LOG.CLIENT_IP IS '客户端地址';;
COMMENT ON COLUMN SYS_LOG.REQUEST_URL IS '请求路径';;
COMMENT ON COLUMN SYS_LOG.REQUEST_PARAM IS '请求参数';;
COMMENT ON COLUMN SYS_LOG.RESPONSE_RESULT IS '响应结果';;
COMMENT ON COLUMN SYS_LOG.EXECUTE_METHOD IS '执行方法';;
COMMENT ON COLUMN SYS_LOG.EXECUTE_TIME IS '执行时间';;
COMMENT ON COLUMN SYS_LOG.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_LOG.CREATED_TIME IS '创建时间';;

DROP TABLE SYS_JOB;;

CREATE TABLE SYS_JOB(
    ID_ VARCHAR2(32) NOT NULL,
    NAME_ VARCHAR2(200) NOT NULL,
    CRON_ VARCHAR2(100) NOT NULL,
    PARAM_ VARCHAR2(500),
    DESC_ VARCHAR2(500) NOT NULL,
    STATUS_ VARCHAR2(10) NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    DELETE_FLAG CHAR(1) NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_JOB IS '任务表';;
COMMENT ON COLUMN SYS_JOB.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_JOB.NAME_ IS '类名';;
COMMENT ON COLUMN SYS_JOB.CRON_ IS '时间';;
COMMENT ON COLUMN SYS_JOB.PARAM_ IS '参数';;
COMMENT ON COLUMN SYS_JOB.DESC_ IS '描述';;
COMMENT ON COLUMN SYS_JOB.STATUS_ IS '状态';;
COMMENT ON COLUMN SYS_JOB.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_JOB.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_JOB.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_JOB.UPDATED_TIME IS '更新时间';;
COMMENT ON COLUMN SYS_JOB.DELETE_FLAG IS '删除标记';;

DROP TABLE SYS_JOB_LOG;;

CREATE TABLE SYS_JOB_LOG(
    ID_ VARCHAR2(32) NOT NULL,
    JOB_ID VARCHAR2(32) NOT NULL,
    PARAM_ CLOB,
    RESULT_ CLOB NOT NULL,
    SERVER_ VARCHAR2(100) NOT NULL,
    BEGIN_TIME DATE NOT NULL,
    END_TIME DATE NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_)
);;

COMMENT ON TABLE SYS_JOB_LOG IS '任务日志表';;
COMMENT ON COLUMN SYS_JOB_LOG.ID_ IS 'ID';;
COMMENT ON COLUMN SYS_JOB_LOG.JOB_ID IS '任务ID';;
COMMENT ON COLUMN SYS_JOB_LOG.PARAM_ IS '参数';;
COMMENT ON COLUMN SYS_JOB_LOG.RESULT_ IS '结果';;
COMMENT ON COLUMN SYS_JOB_LOG.SERVER_ IS '服务器';;
COMMENT ON COLUMN SYS_JOB_LOG.BEGIN_TIME IS '开始时间';;
COMMENT ON COLUMN SYS_JOB_LOG.END_TIME IS '结束时间';;
COMMENT ON COLUMN SYS_JOB_LOG.CREATED_TIME IS '创建时间';;

DROP TABLE SYS_SEQ;;

CREATE TABLE SYS_SEQ(
    CODE_ VARCHAR2(32) NOT NULL,
    PREFIX_ VARCHAR2(50) NOT NULL,
    VALUE_ INT NOT NULL,
    LENGTH_ INT NOT NULL,
    PRIMARY KEY (CODE_)
);;

COMMENT ON TABLE SYS_SEQ IS '序列表';;
COMMENT ON COLUMN SYS_SEQ.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_SEQ.PREFIX_ IS '前缀';;
COMMENT ON COLUMN SYS_SEQ.VALUE_ IS '初始值';;
COMMENT ON COLUMN SYS_SEQ.LENGTH_ IS '长度';;

DROP TABLE SYS_SEQ_DTL;;

CREATE TABLE SYS_SEQ_DTL(
    CODE_ VARCHAR2(32) NOT NULL,
    PREFIX_ VARCHAR2(50) NOT NULL,
    VALUE_ INT NOT NULL,
    PRIMARY KEY (CODE_,PREFIX_)
);;

COMMENT ON TABLE SYS_SEQ_DTL IS '序列明细表';;
COMMENT ON COLUMN SYS_SEQ_DTL.CODE_ IS '代码';;
COMMENT ON COLUMN SYS_SEQ_DTL.PREFIX_ IS '前缀';;
COMMENT ON COLUMN SYS_SEQ_DTL.VALUE_ IS '当前值';;

DROP TABLE SYS_REPORT_FILE;;

CREATE TABLE SYS_REPORT_FILE(
    FILE_ VARCHAR2(50) NOT NULL,
    CONTENT_ CLOB NOT NULL,
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(32),
    UPDATED_TIME TIMESTAMP,
    PRIMARY KEY (FILE_)
);;

COMMENT ON TABLE SYS_REPORT_FILE IS '报表文件表';;
COMMENT ON COLUMN SYS_REPORT_FILE.FILE_ IS '文件';;
COMMENT ON COLUMN SYS_REPORT_FILE.CONTENT_ IS '内容';;
COMMENT ON COLUMN SYS_REPORT_FILE.CREATED_BY IS '创建人';;
COMMENT ON COLUMN SYS_REPORT_FILE.CREATED_TIME IS '创建时间';;
COMMENT ON COLUMN SYS_REPORT_FILE.UPDATED_BY IS '更新人';;
COMMENT ON COLUMN SYS_REPORT_FILE.UPDATED_TIME IS '更新时间';;

