DROP TABLE IF EXISTS FLOW_PROCESS_FILE;;

CREATE TABLE FLOW_PROCESS_FILE(
    FILE_ VARCHAR(50) NOT NULL   COMMENT '文件' ,
    CONTENT_ TEXT NOT NULL   COMMENT '内容' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (FILE_)
) COMMENT = '流程文件表';;

