DROP TABLE IF EXISTS SYS_PARAM;;

CREATE TABLE SYS_PARAM(
    CODE_ VARCHAR(32) NOT NULL   COMMENT '代码' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '名称' ,
    VALUE_ VARCHAR(500) NOT NULL   COMMENT '内容' ,
    SORT_ INT NOT NULL   COMMENT '顺序' ,
    PRIMARY KEY (CODE_)
) COMMENT = '参数表';;

DROP TABLE IF EXISTS SYS_DICT;;

CREATE TABLE SYS_DICT(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '名称' ,
    SORT_ INT NOT NULL   COMMENT '顺序' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '字典表';;

DROP TABLE IF EXISTS SYS_DICT_ITEM;;

CREATE TABLE SYS_DICT_ITEM(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    DICT_ID VARCHAR(32) NOT NULL   COMMENT '类型' ,
    CODE_ VARCHAR(10) NOT NULL   COMMENT '代码' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '名称' ,
    SORT_ INT NOT NULL   COMMENT '顺序' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '字典项目表';;

DROP TABLE IF EXISTS SYS_ORGAN;;

CREATE TABLE SYS_ORGAN(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    CODE_ VARCHAR(50) NOT NULL   COMMENT '代码' ,
    NAME_ VARCHAR(200) NOT NULL   COMMENT '名称' ,
    PID_ VARCHAR(32) NOT NULL   COMMENT '上级ID' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '机构表';;

DROP TABLE IF EXISTS SYS_RES;;

CREATE TABLE SYS_RES(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '名称' ,
    TYPE_ VARCHAR(10) NOT NULL   COMMENT '类型' ,
    ICON_ VARCHAR(50)    COMMENT '图标' ,
    URL_ VARCHAR(500)    COMMENT '路径' ,
    SORT_ INT NOT NULL   COMMENT '顺序' ,
    SHOW_ VARCHAR(10) NOT NULL   COMMENT '显示' ,
    PID_ VARCHAR(32) NOT NULL   COMMENT '上级ID' ,
    PRIMARY KEY (ID_)
) COMMENT = '资源表';;

DROP TABLE IF EXISTS SYS_ROLE;;

CREATE TABLE SYS_ROLE(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    CODE_ VARCHAR(50) NOT NULL   COMMENT '代码' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '名称' ,
    PID_ VARCHAR(32) NOT NULL   COMMENT '上级ID' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '角色表';;

DROP TABLE IF EXISTS SYS_ROLE_RES;;

CREATE TABLE SYS_ROLE_RES(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    ROLE_ID VARCHAR(32) NOT NULL   COMMENT '角色ID' ,
    RES_ID VARCHAR(32) NOT NULL   COMMENT '资源ID' ,
    PRIMARY KEY (ID_)
) COMMENT = '角色资源表';;

DROP TABLE IF EXISTS SYS_USER;;

CREATE TABLE SYS_USER(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    ACCOUNT_ VARCHAR(50) NOT NULL   COMMENT '帐号' ,
    PASSWORD_ VARCHAR(32) NOT NULL   COMMENT '密码' ,
    NAME_ VARCHAR(50) NOT NULL   COMMENT '姓名' ,
    LOCKED_ VARCHAR(10) NOT NULL   COMMENT '是否锁定' ,
    ORGAN_ID VARCHAR(32) NOT NULL   COMMENT '机构ID' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '用户表';;

DROP TABLE IF EXISTS SYS_USER_ORGAN;;

CREATE TABLE SYS_USER_ORGAN(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户ID' ,
    ORGAN_ID VARCHAR(32) NOT NULL   COMMENT '机构ID' ,
    PRIMARY KEY (ID_)
) COMMENT = '用户机构表';;

DROP TABLE IF EXISTS SYS_USER_ROLE;;

CREATE TABLE SYS_USER_ROLE(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户ID' ,
    ROLE_ID VARCHAR(32) NOT NULL   COMMENT '角色ID' ,
    PRIMARY KEY (ID_)
) COMMENT = '用户角色表';;

DROP TABLE IF EXISTS SYS_USER_RES;;

CREATE TABLE SYS_USER_RES(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户ID' ,
    RES_ID VARCHAR(32) NOT NULL   COMMENT '资源ID' ,
    PRIMARY KEY (ID_)
) COMMENT = '用户资源表';;

DROP TABLE IF EXISTS SYS_LOG;;

CREATE TABLE SYS_LOG(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    TYPE_ VARCHAR(10) NOT NULL   COMMENT '类型' ,
    CONTENT_ VARCHAR(200) NOT NULL   COMMENT '内容' ,
    CLIENT_IP VARCHAR(100) NOT NULL   COMMENT '客户端地址' ,
    REQUEST_URL VARCHAR(200) NOT NULL   COMMENT '请求路径' ,
    REQUEST_PARAM TEXT    COMMENT '请求参数' ,
    RESPONSE_RESULT TEXT NOT NULL   COMMENT '响应结果' ,
    EXECUTE_METHOD VARCHAR(500) NOT NULL   COMMENT '执行方法' ,
    EXECUTE_TIME BIGINT NOT NULL   COMMENT '执行时间' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    PRIMARY KEY (ID_)
) COMMENT = '日志表';;

DROP TABLE IF EXISTS SYS_JOB;;

CREATE TABLE SYS_JOB(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    NAME_ VARCHAR(200) NOT NULL   COMMENT '类名' ,
    CRON_ VARCHAR(100) NOT NULL   COMMENT '时间' ,
    PARAM_ VARCHAR(500)    COMMENT '参数' ,
    DESC_ VARCHAR(500) NOT NULL   COMMENT '描述' ,
    STATUS_ VARCHAR(10) NOT NULL   COMMENT '状态' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DELETE_FLAG CHAR(1) NOT NULL   COMMENT '删除标记' ,
    PRIMARY KEY (ID_)
) COMMENT = '任务表';;

DROP TABLE IF EXISTS SYS_JOB_LOG;;

CREATE TABLE SYS_JOB_LOG(
    ID_ VARCHAR(32) NOT NULL   COMMENT 'ID' ,
    JOB_ID VARCHAR(32) NOT NULL   COMMENT '任务ID' ,
    PARAM_ TEXT    COMMENT '参数' ,
    RESULT_ TEXT NOT NULL   COMMENT '结果' ,
    SERVER_ VARCHAR(100) NOT NULL   COMMENT '服务器' ,
    BEGIN_TIME DATETIME NOT NULL   COMMENT '开始时间' ,
    END_TIME DATETIME NOT NULL   COMMENT '结束时间' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    PRIMARY KEY (ID_)
) COMMENT = '任务日志表';;

DROP TABLE IF EXISTS SYS_SEQ;;

CREATE TABLE SYS_SEQ(
    CODE_ VARCHAR(32) NOT NULL   COMMENT '代码' ,
    PREFIX_ VARCHAR(50) NOT NULL   COMMENT '前缀' ,
    VALUE_ INT NOT NULL   COMMENT '初始值' ,
    LENGTH_ INT NOT NULL   COMMENT '长度' ,
    PRIMARY KEY (CODE_)
) COMMENT = '序列表';;

DROP TABLE IF EXISTS SYS_SEQ_DTL;;

CREATE TABLE SYS_SEQ_DTL(
    CODE_ VARCHAR(32) NOT NULL   COMMENT '代码' ,
    PREFIX_ VARCHAR(50) NOT NULL   COMMENT '前缀' ,
    VALUE_ INT NOT NULL   COMMENT '当前值' ,
    PRIMARY KEY (CODE_,PREFIX_)
) COMMENT = '序列明细表';;

DROP TABLE IF EXISTS SYS_REPORT_FILE;;

CREATE TABLE SYS_REPORT_FILE(
    FILE_ VARCHAR(50) NOT NULL   COMMENT '文件' ,
    CONTENT_ TEXT NOT NULL   COMMENT '内容' ,
    CREATED_BY VARCHAR(32) NOT NULL   COMMENT '创建人' ,
    CREATED_TIME DATETIME NOT NULL   COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (FILE_)
) COMMENT = '报表文件表';;

